<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_6</name>
   <tag></tag>
   <elementGuidId>493b6773-a903-4c28-9304-70a1a28a4b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::div[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ant-picker-cell.ant-picker-cell-in-view.ant-picker-cell-range-hover-end > div.ant-picker-cell-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .ant-picker-date-panel > .ant-picker-body > .ant-picker-content > tbody > tr:nth-child(2) > td:nth-child(2) > .ant-picker-cell-inner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8946aee8-982d-4e80-b714-6700022455f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-picker-cell-inner</value>
      <webElementGuid>d96875d1-5244-487f-8480-e6078006def4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c8915f2c-f4f7-4c77-b560-3801fb356ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[9]/div[1]/div[@class=&quot;ant-picker-dropdown ant-picker-dropdown-range ant-picker-dropdown-placement-bottomLeft&quot;]/div[@class=&quot;ant-picker-range-wrapper ant-picker-date-range-wrapper&quot;]/div[@class=&quot;ant-picker-panel-container&quot;]/div[@class=&quot;ant-picker-panels&quot;]/div[@class=&quot;ant-picker-panel ant-picker-panel-has-range-hover&quot;]/div[@class=&quot;ant-picker-date-panel&quot;]/div[@class=&quot;ant-picker-body&quot;]/table[@class=&quot;ant-picker-content&quot;]/tbody[1]/tr[2]/td[@class=&quot;ant-picker-cell ant-picker-cell-in-view ant-picker-cell-range-hover-end&quot;]/div[@class=&quot;ant-picker-cell-inner&quot;]</value>
      <webElementGuid>5ac6958c-1d1a-4465-b4f6-0ab00fd629cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::div[9]</value>
      <webElementGuid>8d89da07-0703-4061-9157-f176865371b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::div[9]</value>
      <webElementGuid>cc7eb107-231b-4a6e-ad18-efde88b31f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/table/tbody/tr[2]/td[2]/div</value>
      <webElementGuid>4037c67d-95e6-439e-8d21-9c843026309a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '6' or . = '6')]</value>
      <webElementGuid>289f91a4-79b5-4baa-bf77-9344791803a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
